/*
 * WARNING: DO NOT CHANGE THIS FILE!
 * This file is automatically generated from createconf
 * using Microsoft Visual C++ under MS Windows(TM) the Sep 26 2005
 */

#ifndef _DUMA_CONFIG_H_
#define _DUMA_CONFIG_H_

/*
 * Number of bytes per virtual-memory page, as returned by Page_Size().
 */
#define DUMA_PAGE_SIZE 4096

/*
 * Minimum required alignment by CPU.
 */
#define DUMA_MIN_ALIGNMENT 1

/*
 * Build environment supports the '__attribute ((constructor))'?
 */
/* #define DUMA_GNU_INIT_ATTR 0 */

/*
 * An integer type with same size as 'void *'
 */
typedef unsigned int DUMA_ADDR;

/*
 * An integer type with same size as 'size_t'
 */
typedef unsigned int DUMA_SIZE;

#endif /* _DUMA_CONFIG_H_ */
