/*
 * WARNING: DO NOT CHANGE THIS FILE!
 * This file is automatically generated from createconf
 * using Microsoft Visual C++ under MS Windows(TM) the Jan  4 2005
 */

#ifndef _EFENCE_CONFIG_H_
#define _EFENCE_CONFIG_H_

/*
 * Number of bytes per virtual-memory page, as returned by Page_Size().
 */
#define EF_PAGE_SIZE 4096

#endif /* _EFENCE_CONFIG_H_ */
