#=======================================================================
#@V@:Note: File automatically generated by VIDE: (20:27:22 22 Nov 2002) (BCC32).
#  This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
.AUTODEPEND

# Borland C++ tools
IMPLIB	= $(BCCROOT)\bin\Implib
ILINK32	= $(BCCROOT)\bin\ILink32
TLIB	= $(BCCROOT)\bin\TLib
BRC32	= $(BCCROOT)\bin\Brc32
TASM32	= $(BCROOT)\bin\Tasm32
CC  	= $(BCCROOT)\bin\BCC32

BCCROOT	= C:\borland\bcc55

HOMEV	=	
VPATH	=	$(HOMEV)\include
oDir	=	.
Bin	=	.
Src	=	.
libDirs	=	-L$(BCCROOT)\lib;$(BCCROOT)\lib\psdk;..\efencelib

incDirs	=	-I$(BCCROOT)\include

LIBS	=	-v -Tpe -ap -c   
C_FLAGS	=	-q -v\
	-D_WINVER=0x0400\
	-D_WIN32_WINNT=0x0400\
	-DWIN32

SRCS	=\
	$(Src)\..\..\eftest.c

EXOBJS	=\
	$(oDir)\eftest.obj

ALLOBJS	=	$(EXOBJS)
BCCJUNK	=	*.il* *.csm *.tds
ALLBIN	=	$(Bin)\eftest
ALLTGT	=	$(Bin)\eftest

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN) $(BCCJUNK)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------

# BCC32 DEF file: add after = if needed
BCC32DEF =
# BCC32 RT lib: cw32.lib static
BCC32RTLIB = cw32
# BCC32 Startup: c0x32.obj-console, c0w32.obj-winapi
BCC32STARTUP = c0x32.obj

#@# Dependency rules follow -----------------------------

$(Bin)\eftest : $(EXOBJS)
  $(ILINK32) @&&|
 $(LIBS) $(libDirs) +
$(BCC32STARTUP) +
$(oDir)\eftest.obj
$<,$*
import32.lib +
$(BCC32RTLIB).lib +
efencelib.lib
$(BCC32DEF)


|
$(oDir)\eftest.obj : $(Src)\..\..\eftest.c
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ $(Src)\..\..\eftest.c

