name: OSSAR
on:
  push:
  pull_request:
jobs:
  OSSAR-Scan:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        fetch-depth: 2
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    - name: Run OSSAR
      uses: github/ossar-action@v2
      id: ossar
    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
